### ISSUE TITLE
Using SETNX and TTL in a MULTI

### ISSUE THREAD

**Issue by heroic** [classdojo/rolling-rate-limiter#1]
If say you wanted to perform an action 10 times a minute and also maintain a gap(in other words, time between action to be 6 seconds), could you simply not have done this:

1) Use SETNX, if you are able to do it, then set a TTL of 6 seconds on the key. Do these in a MULTI.
2) Perform action.

Now you have rate limiting as well as gap between actions. Also, no blocked actions, will affect anything. If I got something wrong from your post, do let me know.

**Comment by peterkhayes** [comment]
Hi Heroic,

I'm not sure I fully understand your suggestion.  SETNX + EXPIRE can definitely be used to provide a gap between actions.  But how does your approach handle rate limiting with a rolling window?  Do you mean you want to combine this with another rate limiter?  If so, how does that limiter provide rolling window support?

**Comment by cdolivares** [comment]
Hey Heroic -

The SETNX approach does implement rate limiting within a certain window, but it couples the length of the rolling window with the minimum time between actions.  For instance, the minimum time between actions given a rolling window of 1 minute with 10 allowable actions within that window must always be 6 seconds.  You may, instead, want to allow at most 10 actions within 1 minute with a minimum time of 1 second between them, which the SETNX approach would not support.
