### ISSUE TITLE
API call hangs if redis goes down

### ISSUE THREAD

**Issue by rohitvyavahare** [classdojo/rolling-rate-limiter#13]
We are using your module to rate limit across multiple instances using redis. 
So, when redis goes down and our apis get called, the api call hangs. Should we manage redis connection and errors in our application or are you planning to add those checks in your module?

**Comment by raymondfeng** [comment]
This module expects a Redis client to be created. If you use `redis`, you might have to customize the `retry_strategy` in `options` per https://github.com/NodeRedis/node_redis#rediscreateclient. For example,
```
var client = redis.createClient({
    retry_strategy: function (options) {
        if (options.error.code === 'ECONNREFUSED') {
            // End reconnecting on a specific error and flush all commands with a individual error
            return new Error('The server refused the connection');
        }
        if (options.total_retry_time > 1000 * 60 * 60) {
            // End reconnecting after a specific timeout and flush all commands with a individual error
            return new Error('Retry time exhausted');
        }
        if (options.times_connected > 10) {
            // End reconnecting with built in error
            return undefined;
        }
        // reconnect after
        return Math.max(options.attempt * 100, 3000);
    }
});
```

**Comment by zeenatl** [comment]
We are wondering if this can somehow be built into the rate limiter module instead of every client having to handle this themselves. The client would get an error back if redis is down and it would be upto the client on how to handle that error.
