### ISSUE TITLE
limiter gives wrong timeleft when minDifference is defined

### ISSUE THREAD

**Issue by rohitvyavahare** [classdojo/rolling-rate-limiter#14]
How to reproduce issue:

I have a limiter defined as follow

``` node
var limiter = RateLimiter({
   redis: client,
   namespace: 'test',
   interval: 6000,
   maxInInterval: 2,
   minDifference: 1000
 });
```

consider I make the first request at t0, second request after 2 seconds at t1 and third request after 2 seconds at t2. So, instead of giving me 2 seconds as time left with 429 status code , it gives me a negative number as time left with 429 status code .

so from code I can see when tooManyInInterval is true and timeSinceLastRequest is greater than minDifference, it goes in if section and try to get min using following code:

``` node
Math.min(userSet[0] - now + interval, minDifference ? minDifference - timeSinceLastRequest : Infinity);
```

so as minDifference is defined and timeSinceLastRequest is greater than minDifference it gives result in minus

If minDifference is not defined code works fine

**Comment by peterkhayes** [comment]
This has been merged and published as 0.1.7.  Sorry for the delays.
