### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by allen1200** [classdojo/rolling-rate-limiter#9]
I'm not sure if this is intended or not, but I think there's a terrible bug where if you set the interval to say 10 requests per 10 minutes, and the user requests come in a 2 per minute rate. That user will always be blocked, where 10 out of those 20 requests should get in and 10 blocked.

Each time it'll reset update window whether or not the request has been fulfilled.

**Comment by neverfox** [comment]
It was intended and is documented in the README:

```
Note: if an action is blocked, it is still added to the set. This means that if a user is continually attempting actions more quickly than the allowed rate, all of their actions will be blocked until they pause or slow their requests.
```

This limitation is the result of the fact that the solution here doesn't require a separate process to maintain the rate limit. It's a tradeoff that might not be acceptable for your use case.

**Comment by peterkhayes** [comment]
This is correct.  Thanks, @neverfox!
